---
title: "Essay II: main results"
author: "João Ricardo Tonin"
date: 2021-11-15T17:42:34-03:00
draft: false
output:
  md_document:
    variant: markdown
    preserve_yaml: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# define memory limit
memory.limit(size = 999999999999)

{ 
  # Check if the packages that we need are installed
  want = c("tidyverse", "plm", "texreg", "lmtest", "tibble",
           "gluedown", "stringr", "rvest", "kableExtra")
  have = want %in% rownames(installed.packages())
  # Install the packages that we miss
  if ( any(!have) ) { install.packages( want[!have] ) }
  # Load the packages
  junk <- lapply(want, library, character.only = T)
  # Remove the objects we created
  rm(have, want, junk)
} # Import packages

```

```{r reading_databases, include=FALSE, echo=TRUE}

# reading log databases
LBASE1 = readRDS(url("https://github.com/jrtonin/thesis_essay_ii/raw/main/data/LBASE1_Essay_II.rds"))
LBASE1c = readRDS(url("https://github.com/jrtonin/thesis_essay_ii/raw/main/data/LBASE1c_Essay_II.rds"))
LBASE2 = readRDS(url("https://github.com/jrtonin/thesis_essay_ii/raw/main/data/LBASE2_Essay_II.rds"))
LBASE2c = readRDS(url("https://github.com/jrtonin/thesis_essay_ii/raw/main/data/LBASE2c_Essay_II.rds"))

# read normal databases
BASE1 = readRDS(url("https://github.com/jrtonin/thesis_data/raw/main/data/final/BASE1_Essay_II.rds"))
BASE2 = readRDS(url("https://github.com/jrtonin/thesis_data/raw/main/data/final/BASE2_Essay_II.rds"))

```

```{r sd_full, include=TRUE, echo=FALSE}

## organizing database

# applying mean operation
sdfulla = BASE1 %>% ungroup() %>%
  group_by(covid_wave) %>%
  summarise(across(c(price, hubling, aircraft, flight_hours, take_off, RouteShare, tx_seat, 
         free_luggage, paid_luggage, `0-5`, `6-11`, `12-17`, `18-23`, DepHUB,          
         capital_dep, ArrHUB, capital_arr), ~ mean(.x, na.rm = TRUE))) %>%
  mutate(covid_wave = case_when(covid_wave == "normal" ~ 1,
                                covid_wave == "first" ~ 3,
                                covid_wave == "second" ~ 5, TRUE ~ 0))

# applying sd operation
sdfullb = BASE1 %>% ungroup() %>%
  group_by(covid_wave) %>%
  summarise(across(c(price, hubling, aircraft, flight_hours, take_off, RouteShare, tx_seat, 
         free_luggage, paid_luggage, `0-5`, `6-11`, `12-17`, `18-23`, DepHUB,          
         capital_dep, ArrHUB, capital_arr), ~ sd(.x, na.rm = TRUE))) %>%
  mutate(covid_wave = case_when(covid_wave == "normal" ~ 2,
                                covid_wave == "first" ~ 4,
                                covid_wave == "second" ~ 6, TRUE ~ 0))

# merging mean and sd databases
sdfull = sdfulla %>%
  bind_rows(sdfullb) %>%
  arrange(covid_wave) %>%
  mutate(across(c(price, hubling, aircraft, flight_hours, take_off, RouteShare, tx_seat, 
         free_luggage, paid_luggage, `0-5`, `6-11`, `12-17`, `18-23`, DepHUB,          
         capital_dep, ArrHUB, capital_arr), ~ round(.x, 2))) %>%
  mutate(covid_wave = case_when(covid_wave == 1 ~ "normal_mean",
                                covid_wave == 2 ~ "normal_sd",
                                covid_wave == 3 ~ "first_mean",
                                covid_wave == 4 ~ "first_sd",
                                covid_wave == 5 ~ "second_mean",
                                covid_wave == 6 ~ "second_sd", TRUE ~ "erro")) %>%
  gather(variable,value,price:capital_arr) %>%
  spread(covid_wave,value)
  
print(sdfull)

```


```{r databases, warning=FALSE, message=FALSE, error=FALSE, include=TRUE, echo = FALSE}

{
# organizing database
dLBASE1 = LBASE1 %>% 
  ungroup() %>%
  arrange(year, month, air_dep, air_arr, airline) %>%
  group_by(year, month) %>% 
  mutate(id = sequence(n()),
         time = paste0(year,"/", month))

# creating group indices' variable
dLBASE1$group = dLBASE1 %>% group_indices(time)

# transforming to panel data
dLBASE1 = pdata.frame(dLBASE1, index = c("id","time")) %>%
  ungroup() %>% arrange(year, month)

} # organizing LBASE1

{
# organizing database
dLBASE1c = LBASE1c %>% 
  ungroup() %>%
  arrange(year, month, air_dep, air_arr, airline) %>%
  group_by(year, month) %>% 
  mutate(id = sequence(n()),
         time = paste0(year,"/", month))

# creating group indices' variable
dLBASE1c$group = dLBASE1c %>% group_indices(time)

# transforming to panel data
dLBASE1c = pdata.frame(dLBASE1c, index = c("id","time")) %>%
  ungroup() %>% arrange(year, month)

} # organizing LBASE1c

{
# organizing database
dLBASE2 = LBASE2 %>% 
  ungroup() %>%
  arrange(year, month, air_dep, air_arr) %>%
  group_by(year, month) %>% 
  mutate(id = sequence(n()),
         time = paste0(year,"/", month))

# creating group indices' variable
dLBASE2$group = dLBASE2 %>% group_indices(time)

# transforming to panel data
dLBASE2 = pdata.frame(dLBASE2, index = c("id","time")) %>%
  ungroup() %>% arrange(year, month)

} # organizing LBASE2

{
# organizing database
dLBASE2c = LBASE2c %>% 
  ungroup() %>%
  arrange(year, month, air_dep, air_arr) %>%
  group_by(year, month) %>% 
  mutate(id = sequence(n()),
         time = paste0(year,"/", month))

# creating group indices' variable
dLBASE2c$group = dLBASE2c %>% group_indices(time)

# transforming to panel data
dLBASE2c = pdata.frame(dLBASE2c, index = c("id","time")) %>%
  ungroup() %>% arrange(year, month)

} # organizing LBASE2c


```

```{r base1, include = TRUE, echo = FALSE}

# dummies | Tourist | N | market | covid | covid_wave | quarter | airline
# arrival dummies | ArrHUB | market_arr | region_arr | capital_arr 
# departure dummies | DepHUB | market_dep | capital_dep | region_dep

# defining equations
OLS = price ~  hubling + aircraft + flight_hours +  
  connection + X6.11 + X12.17 + X18.23 + RouteShare + factor(Tourist) + factor(N)  + 
  factor(covid) + factor(covid_wave) + factor(quarter) + factor(ArrHUB) + factor(market_arr) +
  factor(capital_arr)

IV = price ~ hubling + aircraft + flight_hours +  
  connection + X6.11 + X12.17 + X18.23 + RouteShare + factor(Tourist) + factor(N) +  
  factor(covid) + factor(covid_wave) + factor(quarter) + factor(ArrHUB) + factor(market_arr) +
  factor(capital_arr) | . -RouteShare + m150RouteShare

GMM = price ~ lag(price) + hubling + aircraft + flight_hours +  
  connection + X6.11 + X12.17 + X18.23 + RouteShare | lag(RouteShare, 1:10) + lag(price, 2:10) + m150RouteShare 

# regression
ols = plm(OLS, data = dLBASE1, model = "pooling")
fe =  plm(OLS, data = dLBASE1, effect = "individual")
ivfe = update(fe, IV)

# ec2sls
ecw1 = plm(IV, data = dLBASE1, model = "within")
ecr1 = update(ecw1, model = "random", random.method = "nerlove", inst.method = "baltagi")

# Hausman test
#phtest(ecw1, ecr1) # H1: one model is inconsistent - p_valor < 0,10 : within

# ht2sls

# ec
ht1r = plm(IV, data = dLBASE1, model = "random", 
           inst.method = "baltagi", random.method = "ht")
# w
ht1w = plm(IV, data = dLBASE1, model = "within", 
           inst.method = "baltagi", random.method = "ht")

# Hausman test
#phtest(ht1w, ht1r)

# gmm  
gmm = pgmm(GMM, dLBASE1, model = "onestep", effect="individual")

# joining regression results
screenreg(list(ols = ols, fe = fe, ivfe = ivfe, ecw1 = ecw1, ht1r = ht1r, gmm = gmm),
               digits = 3, omit.coef = "(Intercept)")

```

